### PR TITLE
New blog article: Introducing the New Sample Torrent Migration Tool

### LINKED ISSUE #85: New blog post: about the sample importer script
See: https://github.com/torrust/torrust-index-backend/discussions/268

### PR DESCRIPTION
**Pull request by josecelano**

### CODE REVIEW

**Comment by da2ce7** [comment]
@josecelano Post-Merge, wow! 14.9 MB https://github.com/torrust/torrust-website/blob/develop/static/images/posts/pexels-david-dibert-7177008.png
PNG image that should really be a correctly optimized JPEG.

**Comment by josecelano** [comment]
> @josecelano Post-Merge, wow! 14.9 MB https://github.com/torrust/torrust-website/blob/develop/static/images/posts/pexels-david-dibert-7177008.png PNG image that should really be a correctly optimized JPEG.

I wasn't sure which size would be OK. Right now, we only show the image like this:

image

But in the future, we could change the template. I can't make it smaller and keep the original one in a different folder.

@matfantinel would be OK a 667x344px PNG?

In webp format the same image with a 90% quality is only 943K. But GitHub does not even support it yet. In JPG is 1.8 MB.

- Should we use webp?
- Should we use jpeg?
- Should we make them smaller? If yes, what size?

**Comment by da2ce7** [comment]
we should use jpeg for photos and png for images, once jpegXL has support everywhere we move to it. :)

**Comment by josecelano** [comment]
> we should use jpeg for photos and png for images, once jpegXL has support everywhere we move to it. :)

OK @da2ce7 , should we also decrease the size? For example to a maximum width. And store the original?

**Comment by da2ce7** [comment]
Hmmm... well looked at the other images, they are around 1mb, I think that they are fine. :)

**Pull request merged**
