### PR TITLE
#81 New blog posts: What a torrent tracker is and their types.

### LINKED ISSUE #81: New blog post: What a torrent tracker is and their types.
Basic article about what a torrent tracker is and the two types of trackers, public and private.

### PR DESCRIPTION
**Pull request by mario-nt**
Resolves #81

### CODE REVIEW

**Comment by cgbosse** [comment]
@josecelano please have a look at this.

**Comment by mario-nt** [comment]
It looks like it is a formatting error, I will check it out too.

**Comment by mario-nt** [comment]
Pushed new commit after fixing the issue. @cgbosse Can you please run the workflow again? Thanks

**Comment by josecelano** [comment]
Hi @mario-nt I think it's a good introductory article. I have a couple of suggestions:

1. I would change the cover image. Maybe we can add a diagram with peers/trackers (very technical) or something more decorative. That diagram explains how the tracker fits into the Torrust Solution architecture.
2. Something that has always been very confusing for me is the way we use the term "tracker". Sometimes is only the tracker (service described on [BEP 03](https://www.bittorrent.org/beps/bep_0003.html) and [BEP 15](https://www.bittorrent.org/beps/bep_0015.html)) and sometimes is actually used to refer to the Torrents Index Website (a website where you can search for torrents and download them). I would clarify those concepts in the article.

### Introduction

Torrents are often associated with a program used for downloading files from a network of people via the internet. However, the term 'tracker' can sometimes be confusing as it is used to refer to two different things: the service described in the BitTorrent Enhancement Proposals (BEPs) (UDP and HTTP trackers), and a Torrent Index, which is a website directory of classified torrents where you can search for torrents.

In this article, I will provide a basic explanation of what a BitTorrent tracker is as described in BEPs, and discuss the two types of trackers: public and private. I will also clarify the distinction between a BitTorrent tracker and a Torrent Index.

### What is a BitTorrent Tracker?

A BitTorrent tracker, as described in BEPs, is essentially an application running on a server that facilitates file sharing among peers using the BitTorrent protocol.

The tracker is responsible for keeping a record of which peer machines (BitTorrent clients and their IPs) possess which files, and whether they are available for sharing. When you add a .torrent file to your torrent client, the tracker informs you where to start downloading parts of the file.

Moreover, the tracker aids in communication between peers and the transmission of data, making the entire process more efficient.

As files are being downloaded, the client periodically communicates with the tracker to send statistics and receive updated information about other peers sharing the files, which can improve download speed.

### Torrent Index vs. BitTorrent Tracker

It is important to differentiate between a BitTorrent tracker and a Torrent Index. A Torrent Index is a website that serves as a directory of classified torrents where users can search for and download torrent files. When you download a torrent file from a Torrent Index site, it usually contains a list of URLs for trackers where your client can request pieces of the torrent. Often, the Torrent Index site has an associated tracker that is included in the list of tracker URLs in the torrent file.

### Public Trackers

Public trackers are accessible to everyone and do not require registration, although some offer benefits to registered users. These trackers usually contain torrent files across various categories like music, films, games, etc. Private trackers usually include only their URLs.

Public trackers are the most straightforward way to access torrents, making them a good starting point for beginners.

However, there are drawbacks to using public trackers:

**Malware Risk**: Torrent files and the website itself may contain malware, as platforms with a large user base are prime targets for malicious actors. Always check for executable files (.exe, .bat, etc.) and read the comments on the torrent file you plan to download. If the torrent is new, consider waiting a few days for others to test the file and comment on any malware presence.

**Privacy Risk**: Without methods to avoid tracking, such as using a VPN, your IP address is publicly accessible. Additionally, public trackers may attract more attention from authorities, increasing the risk of legal repercussions for downloading illegal content.

### Private Trackers

Private trackers require registration, and some are hidden, accessible only through private invitations or a specific process defined by the tracker, which may include an interview.

Private trackers often contain higher quality and hard-to-find torrents. However, they usually require maintaining a good upload-download ratio, meaning you must share files as well as download them, which can be cumbersome.

Despite being private, it is still recommended to use a VPN to increase privacy and security. Your IP address can still be accessed if not hidden, and authorities may monitor private torrents. Additionally, always be cautious of malware on private trackers.

When engaging in the interview process required by some private trackers, exercise common sense regarding sharing private information.

### Conclusion

I hope you found this article useful! Understanding the distinction between a BitTorrent tracker as described in BEPs, a Torrent Index, and the pros and cons of public and private trackers is crucial for anyone using torrents. Happy downloading, but always remember to stay safe and legal!

**Comment by mario-nt** [comment]
Hi @josecelano , I agree with all the feedback you've given me, I will take notes and go ahead and make some changes to the article and the image!

**Review by josecelano — APPROVED** [review]

**Comment by mario-nt** [comment]
@josecelano @cgbosse Cover image updated, fixed typos , and new paragraph about index vs tracker added, ready to be review for merging.

**Comment by josecelano** [comment]
Hi @mario-nt I have made some minor changes [here](https://github.com/torrust/torrust-website/pull/91).

**Pull request closed without merging**
