### PR TITLE
Fix cover image stretching across page, add blog posts to each contributor's page

### PR DESCRIPTION
**Pull request by grmbyrn**
## Description:
This pull request enhances each contributor's page by adding a section at the bottom which displays the blog posts that particular contributor has published. In case a contributor hasn't published any posts, a message is shown indicating that none have been published yet, but to check back soon. On each contributor page, a button displays, either below the posts or the below the aforementioned message, a link back to the page which displays all of the contributors.

Additionally, the cover image layout issue in each blog post, as mentioned in [this issue](https://github.com/torrust/torrust-website/issues/158), has been addressed. The fix prevents the image from stretching across the page and cutting off the top and bottom portions of the image, ensuring a visually pleasing display. Flexbox has been put in place to display the page on large screens similar to the example below should there be interest in it:

Screenshot 2024-03-25 at 18 01 13

Furthermore, the update timestamp, as mentioned in [this issue](https://github.com/torrust/torrust-website/issues/151), has been incorporated into the front matter of each blog post. This feature allows users to see when a post has been last updated, providing valuable information about the post's freshness. If the blog post hasn't been updated then it will not appear on the page until a date for when the update was made has been added.

## Changes:

* Added a section displaying contributor's published posts with a message for no published posts.
* Fixed blog post cover images to prevent stretching and cropping.
* Included update timestamps for each blog post.

### CODE REVIEW

**Review by josecelano — CHANGES_REQUESTED** [review]
Hey @grmbyrn good PR!

In big screens the cover image does not span to use the whole width. Is that the intended behavior?

**Before**

image

**After**

image

**Comment by grmbyrn** [comment]
Hi @josecelano, thanks! I mentioned in [#158](https://github.com/torrust/torrust-website/issues/158) that some images look fine when cropped, like the latest post, but others like the one below gets cut off above and below and looks bad on wider screens.

One idea I had was putting the details to the side on larger screens, or maybe getting multiple sizes of the cover image and setting which one appears depending on page breakpoints for mobile, tablet, and desktop. What do you think?

image

**Comment by josecelano** [comment]
> Hi @josecelano, thanks! I mentioned in [#158](https://github.com/torrust/torrust-website/issues/158) that some images look fine when cropped, like the latest post, but others like the one below gets cut off above and below and looks bad on wider screens.
> 
> One idea I had was putting the details to the side on larger screens, or maybe getting multiple sizes of the cover image and setting which one appears depending on page breakpoints for mobile, tablet, and desktop. What do you think?
> 

Hi @grmbyrn I guess the simplest solution would be just using always the same size (aspect ratio). That would also align images when you have some on them in a row:

image

We can resize them filling with the background color. If it's not possible we can replace them. On the other hand, I think we should use the same style for all of them (maybe). Some of them are realistic, others were generated with ChatGPT in different styles.

Alternatively, we could use different sizes, depending on wether the image is used in a widescreen or a card. Probably that's the best solution. It's also nice when you see these:

image

### Conclusion

- Add different sizes.
- Extend the big size for the images that don't crop well in widescreen.
- We need to change tags to add two images.

What do you think?

**Comment by grmbyrn** [comment]
> > Hi @josecelano, thanks! I mentioned in [#158](https://github.com/torrust/torrust-website/issues/158) that some images look fine when cropped, like the latest post, but others like the one below gets cut off above and below and looks bad on wider screens.
> > One idea I had was putting the details to the side on larger screens, or maybe getting multiple sizes of the cover image and setting which one appears depending on page breakpoints for mobile, tablet, and desktop. What do you think?
> 
> Hi @grmbyrn I guess the simplest solution would be just using always the same size (aspect ratio). That would also align images when you have some on them in a row:
> 
> image
> 
> We can resize them filling with the background color. If it's not possible we can replace them. On the other hand, I think we should use the same style for all of them (maybe). Some of them are realistic, others were generated with ChatGPT in different styles.
> 
> Alternatively, we could use different sizes, depending on wether the image is used in a widescreen or a card. Probably that's the best solution. It's also nice when you see these:
> 
> image
> 
> ### Conclusion
> * Add different sizes.
> * Extend the big size for the images that don't crop well in widescreen.
> * We need to change tags to add two images.
> 
> What do you think?

Hi @josecelano. I would agree that it's best to use different size images on different screens, and also to use the same style image. I think with the images similar to those from the latest blog posts [Profiling the Torrust BitTorrent UDP Tracker](https://torrust.com/profiling-the-torrust-bittorrent-udp-tracker) and [Benchmarking the Torrust BitTorrent Tracker](https://torrust.com/benchmarking-the-torrust-bittorrent-tracker), we would have a nice consistency to suggest that each post is related.

I like the following structure as it takes three separate images and swaps them at the relevant breakpoint:
```
<picture>
       <source media="(min-width: 1100px)" srcset={coverImageDesktop}>
       <source media="(min-width: 768px)" srcset={coverImageTablet}>
       <img src={coverImageMobile} alt="cover">
</picture>
```

Mobile:
Screenshot 2024-03-27 at 11 05 40

Tablet:
Screenshot 2024-03-27 at 11 05 56

Desktop:
Screenshot 2024-03-27 at 11 06 15

**Comment by josecelano** [comment]
> > > Hi @josecelano, thanks! I mentioned in [#158](https://github.com/torrust/torrust-website/issues/158) that some images look fine when cropped, like the latest post, but others like the one below gets cut off above and below and looks bad on wider screens.
> > > One idea I had was putting the details to the side on larger screens, or maybe getting multiple sizes of the cover image and setting which one appears depending on page breakpoints for mobile, tablet, and desktop. What do you think?
> > 
> > 
> > Hi @grmbyrn I guess the simplest solution would be just using always the same size (aspect ratio). That would also align images when you have some on them in a row:
> > image
> > We can resize them filling with the background color. If it's not possible we can replace them. On the other hand, I think we should use the same style for all of them (maybe). Some of them are realistic, others were generated with ChatGPT in different styles.
> > Alternatively, we could use different sizes, depending on wether the image is used in a widescreen or a card. Probably that's the best solution. It's also nice when you see these:
> > image
> > ### Conclusion
> > 
> > * Add different sizes.
> > * Extend the big size for the images that don't crop well in widescreen.
> > * We need to change tags to add two images.
> > 
> > What do you think?
> 
> Hi @josecelano. I would agree that it's best to use different size images on different screens, and also to use the same style image. I think with the images similar to those from the latest blog posts [Profiling the Torrust BitTorrent UDP Tracker](https://torrust.com/profiling-the-torrust-bittorrent-udp-tracker) and [Benchmarking the Torrust BitTorrent Tracker](https://torrust.com/benchmarking-the-torrust-bittorrent-tracker), we would have a nice consistency to suggest that each post is related.
> 
> I like the following structure as it takes three separate images and swaps them at the relevant breakpoint:
> 
> ```
> <picture>
>        <source media="(min-width: 1100px)" srcset={coverImageDesktop}>
>        <source media="(min-width: 768px)" srcset={coverImageTablet}>
>        cover
> </picture>
> ```
> 

Hi @grmbyrn I like that option, however since we are now in the process of re-designing the site maybe we can implement it with the new version. I would suggest merging only the blog post list on the contributor profile and implementing this 3-image feature in the new site version. We could decide to use the same style for our images and it takes time to build the 3 images for all the posts. What do you think?

**Comment by grmbyrn** [comment]
> > > > Hi @josecelano, thanks! I mentioned in [#158](https://github.com/torrust/torrust-website/issues/158) that some images look fine when cropped, like the latest post, but others like the one below gets cut off above and below and looks bad on wider screens.
> > > > One idea I had was putting the details to the side on larger screens, or maybe getting multiple sizes of the cover image and setting which one appears depending on page breakpoints for mobile, tablet, and desktop. What do you think?
> > > 
> > > 
> > > Hi @grmbyrn I guess the simplest solution would be just using always the same size (aspect ratio). That would also align images when you have some on them in a row:
> > > image
> > > We can resize them filling with the background color. If it's not possible we can replace them. On the other hand, I think we should use the same style for all of them (maybe). Some of them are realistic, others were generated with ChatGPT in different styles.
> > > Alternatively, we could use different sizes, depending on wether the image is used in a widescreen or a card. Probably that's the best solution. It's also nice when you see these:
> > > image
> > > ### Conclusion
> > > 
> > > * Add different sizes.
> > > * Extend the big size for the images that don't crop well in widescreen.
> > > * We need to change tags to add two images.
> > > 
> > > What do you think?
> > 
> > 
> > Hi @josecelano. I would agree that it's best to use different size images on different screens, and also to use the same style image. I think with the images similar to those from the latest blog posts [Profiling the Torrust BitTorrent UDP Tracker](https://torrust.com/profiling-the-torrust-bittorrent-udp-tracker) and [Benchmarking the Torrust BitTorrent Tracker](https://torrust.com/benchmarking-the-torrust-bittorrent-tracker), we would have a nice consistency to suggest that each post is related.
> > I like the following structure as it takes three separate images and swaps them at the relevant breakpoint:
> > ```
> > <picture>
> >        <source media="(min-width: 1100px)" srcset={coverImageDesktop}>
> >        <source media="(min-width: 768px)" srcset={coverImageTablet}>
> >        cover
> > </picture>
> > ```
> 
> Hi @grmbyrn I like that option, however since we are now in the process of re-designing the site maybe we can implement it with the new version. I would suggest merging only the blog post list on the contributor profile and implementing this 3-image feature in the new site version. We could decide to use the same style for our images and it takes time to build the 3 images for all the posts. What do you think?

Hi @josecelano, yeah I think it's best to only merge the blog post list and leave the cover image for the new design. I can revert the cover image to how it was.

**Comment by grmbyrn** [comment]
Hi @josecelano I just saw that this PR hasn't been merged. I previously reverted the change to cover images so the only change should be adding the blog posts to each contributor's page. Is there something else that should be changed in this PR?

**Comment by josecelano** [comment]
ACK 0d5a19374cb74a31cf996f4988a3c64c94b4ad76

**Comment by josecelano** [comment]
> Hi @josecelano I just saw that this PR hasn't been merged. I previously reverted the change to cover images so the only change should be adding the blog posts to each contributor's page. Is there something else that should be changed in this PR?

Hi @grmbyrn thank you for the reminder.

**Pull request merged**
