### PR TITLE
feat: add copy button to code block

### PR DESCRIPTION
**Pull request by josecelano**
Relates to: https://github.com/torrust/torrust-website/pull/124

It's just another example of how to add the copy button to the `CodeBlock` component.

### CODE REVIEW

**Review by grmbyrn — COMMENTED** [review]
Hi @josecelano. This looks good and more inline with convention. If you're happy to move forward with it, then I can style and have it added to the page.

**Comment by josecelano** [comment]
> Hi @josecelano. This looks good and more inline with convention. If you're happy to move forward with it, then I can style and have it added to the page.

You can just modify your PR to keep your CSS/UI with this component code.

**Comment by grmbyrn** [comment]
> You can just modify your PR to keep your CSS/UI with this component code.

I already had the changes made to a branch so I just pushed that as it was ready to go. Other branches are ready to go too if all is good here!

**Comment by josecelano** [comment]
ACK de874fd613a885def12734aa02ea95f1e95faa00

**Pull request merged**
