### PR TITLE
Create singletons folder for non-reusable components

### PR DESCRIPTION
**Pull request by grmbyrn**
Created a new folder in `components` called `singletons` for non-reusable components in the following folders:

* `atoms`
* `molecules`
* `organisms`

The stories for each of these components was subsequently removed. As soon as we have two instances of any component in the `singletons` folder, we will extract it into an `atom`, `molecule`, or `organism` and apply a story to it.

### CODE REVIEW

**Review by josecelano — APPROVED** [review]

**Comment by josecelano** [comment]
ACK da292dc059034757f83fa1797d8e5a3bef085f11

**Comment by josecelano** [comment]
Hi @grmbyrn commit is not signed.

**Review by josecelano — CHANGES_REQUESTED** [review]
I've updated the repo rules, which are similar to those of the other repos. Commits must now be signed.

**Comment by grmbyrn** [comment]
> I've updated the repo rules, which are similar to those of the other repos. Commits must now be signed.

Hi @josecelano I just signed the commit but unsure if this is the correct way to do it. I tried generating a GPG key but it wouldn't sign so tried `--signoff` instead.

Is signing something we should do for all PRs going forward?

**Comment by josecelano** [comment]
> > I've updated the repo rules, which are similar to those of the other repos. Commits must now be signed.
> 
> Hi @josecelano I just signed the commit but unsure if this is the correct way to do it. I tried generating a GPG key but it wouldn't sign so tried `--signoff` instead.
> 
> Is signing something we should do for all PRs going forward?

Hi @grmbyrn that's a different feature. See https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

You have to generate your GPG ley, upload the public one to GitHub and setup Git to sign all your commits before pushing to GitHub.

- https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
- https://secure-git.guide/

**Comment by grmbyrn** [comment]
> > > I've updated the repo rules, which are similar to those of the other repos. Commits must now be signed.
> > 
> > 
> > Hi @josecelano I just signed the commit but unsure if this is the correct way to do it. I tried generating a GPG key but it wouldn't sign so tried `--signoff` instead.
> > Is signing something we should do for all PRs going forward?
> 
> Hi @grmbyrn that's a different feature. See https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff
> 
> You have to generate your GPG ley, upload the public one to GitHub and setup Git to sign all your commits before pushing to GitHub.
> 
> * https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
> * https://secure-git.guide/

Hi @josecelano I had set up a GPG key but it wasn't accepting the signature. I made some changes and signed it with  `--gpg-sign`. Is this okay?

**Comment by josecelano** [comment]
> > > > I've updated the repo rules, which are similar to those of the other repos. Commits must now be signed.
> > > 
> > > 
> > > Hi @josecelano I just signed the commit but unsure if this is the correct way to do it. I tried generating a GPG key but it wouldn't sign so tried `--signoff` instead.
> > > Is signing something we should do for all PRs going forward?
> > 
> > 
> > Hi @grmbyrn that's a different feature. See https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff
> > You have to generate your GPG ley, upload the public one to GitHub and setup Git to sign all your commits before pushing to GitHub.
> > 
> > * https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
> > * https://secure-git.guide/
> 
> Hi @josecelano I had set up a GPG key but it wasn't accepting the signature. I made some changes and signed it with `--gpg-sign`. Is this okay?

Hi @grmbyrn, the commit is signed, but I think you have not added the public key to your GitHub profile yet. You have to do this: https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account

image

image

You should have this in your GitHub GPG settings:

image

On the other hand, before signing the commit you can squash all commits in one single commit.

**Comment by grmbyrn** [comment]
> > > > > I've updated the repo rules, which are similar to those of the other repos. Commits must now be signed.
> > > > 
> > > > 
> > > > Hi @josecelano I just signed the commit but unsure if this is the correct way to do it. I tried generating a GPG key but it wouldn't sign so tried `--signoff` instead.
> > > > Is signing something we should do for all PRs going forward?
> > > 
> > > 
> > > Hi @grmbyrn that's a different feature. See https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff
> > > You have to generate your GPG ley, upload the public one to GitHub and setup Git to sign all your commits before pushing to GitHub.
> > > 
> > > * https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
> > > * https://secure-git.guide/
> > 
> > 
> > Hi @josecelano I had set up a GPG key but it wasn't accepting the signature. I made some changes and signed it with `--gpg-sign`. Is this okay?
> 
> Hi @grmbyrn, the commit is signed, but I think you have not added the public key to your GitHub profile yet. You have to do this: https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
> 
> image
> 
> image
> 
> You should have this in your GitHub GPG settings:
> 
> image
> 
> On the other hand, before signing the commit you can squash all commits in one single commit.

Hi @josecelano I added the GPG key to GitHub and resigned the commit. Should I sign every commit I make? Because I've been pushing for months without it and this is the first time I've been asked to sign a commit.

**Comment by josecelano** [comment]
> > > > > > I've updated the repo rules, which are similar to those of the other repos. Commits must now be signed.
> > > > > 
> > > > > 
> > > > > Hi @josecelano I just signed the commit but unsure if this is the correct way to do it. I tried generating a GPG key but it wouldn't sign so tried `--signoff` instead.
> > > > > Is signing something we should do for all PRs going forward?
> > > > 
> > > > 
> > > > Hi @grmbyrn that's a different feature. See https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff
> > > > You have to generate your GPG ley, upload the public one to GitHub and setup Git to sign all your commits before pushing to GitHub.
> > > > 
> > > > * https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
> > > > * https://secure-git.guide/
> > > 
> > > 
> > > Hi @josecelano I had set up a GPG key but it wasn't accepting the signature. I made some changes and signed it with `--gpg-sign`. Is this okay?
> > 
> > 
> > Hi @grmbyrn, the commit is signed, but I think you have not added the public key to your GitHub profile yet. You have to do this: https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
> > image
> > image
> > You should have this in your GitHub GPG settings:
> > image
> > On the other hand, before signing the commit you can squash all commits in one single commit.
> 
> Hi @josecelano I added the GPG key to GitHub and resigned the commit. Should I sign every commit I make? Because I've been pushing for months without it and this is the first time I've been asked to sign a commit.

Hi @grmbyrn, you only need to squash all commits in this PR and sign the final single commit. You don't need to rewrite old commits in this repo or other repos. However, from now on, you should sign all commits in all repos. I thought you knew we were enforcing this practice. Maybe you didn't know because you have pushed only to the website repo and I recently added the rules we have set for the other repos.

**Comment by grmbyrn** [comment]
> > > > > > > I've updated the repo rules, which are similar to those of the other repos. Commits must now be signed.
> > > > > > 
> > > > > > 
> > > > > > Hi @josecelano I just signed the commit but unsure if this is the correct way to do it. I tried generating a GPG key but it wouldn't sign so tried `--signoff` instead.
> > > > > > Is signing something we should do for all PRs going forward?
> > > > > 
> > > > > 
> > > > > Hi @grmbyrn that's a different feature. See https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff
> > > > > You have to generate your GPG ley, upload the public one to GitHub and setup Git to sign all your commits before pushing to GitHub.
> > > > > 
> > > > > * https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
> > > > > * https://secure-git.guide/
> > > > 
> > > > 
> > > > Hi @josecelano I had set up a GPG key but it wasn't accepting the signature. I made some changes and signed it with `--gpg-sign`. Is this okay?
> > > 
> > > 
> > > Hi @grmbyrn, the commit is signed, but I think you have not added the public key to your GitHub profile yet. You have to do this: https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
> > > image
> > > image
> > > You should have this in your GitHub GPG settings:
> > > image
> > > On the other hand, before signing the commit you can squash all commits in one single commit.
> > 
> > 
> > Hi @josecelano I added the GPG key to GitHub and resigned the commit. Should I sign every commit I make? Because I've been pushing for months without it and this is the first time I've been asked to sign a commit.
> 
> Hi @grmbyrn, you only need to squash all commits in this PR and sign the final single commit. You don't need to rewrite old commits in this repo or other repos. However, from now on, you should sign all commits in all repos. I thought you knew we were enforcing this practice. Maybe you didn't know because you have pushed only to the website repo and I recently added the rules we have set for the other repos.

Hi @josecelano I hadn't been told about this practice, but I'll make sure to sign all commits going forward. I've also squashed all the commits in this PR. I signed this one, although there's an Unverified tag on it.

**Comment by josecelano** [comment]
> > > > > > > > I've updated the repo rules, which are similar to those of the other repos. Commits must now be signed.
> > > > > > > 
> > > > > > > 
> > > > > > > Hi @josecelano I just signed the commit but unsure if this is the correct way to do it. I tried generating a GPG key but it wouldn't sign so tried `--signoff` instead.
> > > > > > > Is signing something we should do for all PRs going forward?
> > > > > > 
> > > > > > 
> > > > > > Hi @grmbyrn that's a different feature. See https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff
> > > > > > You have to generate your GPG ley, upload the public one to GitHub and setup Git to sign all your commits before pushing to GitHub.
> > > > > > 
> > > > > > * https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
> > > > > > * https://secure-git.guide/
> > > > > 
> > > > > 
> > > > > Hi @josecelano I had set up a GPG key but it wasn't accepting the signature. I made some changes and signed it with `--gpg-sign`. Is this okay?
> > > > 
> > > > 
> > > > Hi @grmbyrn, the commit is signed, but I think you have not added the public key to your GitHub profile yet. You have to do this: https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
> > > > image
> > > > image
> > > > You should have this in your GitHub GPG settings:
> > > > image
> > > > On the other hand, before signing the commit you can squash all commits in one single commit.
> > > 
> > > 
> > > Hi @josecelano I added the GPG key to GitHub and resigned the commit. Should I sign every commit I make? Because I've been pushing for months without it and this is the first time I've been asked to sign a commit.
> > 
> > 
> > Hi @grmbyrn, you only need to squash all commits in this PR and sign the final single commit. You don't need to rewrite old commits in this repo or other repos. However, from now on, you should sign all commits in all repos. I thought you knew we were enforcing this practice. Maybe you didn't know because you have pushed only to the website repo and I recently added the rules we have set for the other repos.
> 
> Hi @josecelano I hadn't been told about this practice, but I'll make sure to sign all commits going forward. I've also squashed all the commits in this PR. I signed this one, although there's an Unverified tag on it.

Hey @grmbyrn, okay, no problem. That's why we have set the rules for other repos. I think you still need to add the GPG key to your GitHub settings or/and the Gmail email you used for that GPGP Key.

**Comment by grmbyrn** [comment]
> > > > > > > > > I've updated the repo rules, which are similar to those of the other repos. Commits must now be signed.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Hi @josecelano I just signed the commit but unsure if this is the correct way to do it. I tried generating a GPG key but it wouldn't sign so tried `--signoff` instead.
> > > > > > > > Is signing something we should do for all PRs going forward?
> > > > > > > 
> > > > > > > 
> > > > > > > Hi @grmbyrn that's a different feature. See https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff
> > > > > > > You have to generate your GPG ley, upload the public one to GitHub and setup Git to sign all your commits before pushing to GitHub.
> > > > > > > 
> > > > > > > * https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
> > > > > > > * https://secure-git.guide/
> > > > > > 
> > > > > > 
> > > > > > Hi @josecelano I had set up a GPG key but it wasn't accepting the signature. I made some changes and signed it with `--gpg-sign`. Is this okay?
> > > > > 
> > > > > 
> > > > > Hi @grmbyrn, the commit is signed, but I think you have not added the public key to your GitHub profile yet. You have to do this: https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
> > > > > image
> > > > > image
> > > > > You should have this in your GitHub GPG settings:
> > > > > image
> > > > > On the other hand, before signing the commit you can squash all commits in one single commit.
> > > > 
> > > > 
> > > > Hi @josecelano I added the GPG key to GitHub and resigned the commit. Should I sign every commit I make? Because I've been pushing for months without it and this is the first time I've been asked to sign a commit.
> > > 
> > > 
> > > Hi @grmbyrn, you only need to squash all commits in this PR and sign the final single commit. You don't need to rewrite old commits in this repo or other repos. However, from now on, you should sign all commits in all repos. I thought you knew we were enforcing this practice. Maybe you didn't know because you have pushed only to the website repo and I recently added the rules we have set for the other repos.
> > 
> > 
> > Hi @josecelano I hadn't been told about this practice, but I'll make sure to sign all commits going forward. I've also squashed all the commits in this PR. I signed this one, although there's an Unverified tag on it.
> 
> Hey @grmbyrn, okay, no problem. That's why we have set the rules for other repos. I think you still need to add the GPG key to your GitHub settings or/and the Gmail email you used for that GPGP Key.

I already had the GPG key in my GitHub but it still came up unverified. I added the Mailvelope extension to Gmail but I don't know if that works for this.

**Comment by grmbyrn** [comment]
Hi @josecelano I've been able to sign and verify my commit. If all is okay, then it should be ready to be merged.

**Review by josecelano — APPROVED** [review]

**Comment by josecelano** [comment]
ACK 0b446a2bbf3ebc133e8285eb661bcf5827d63f38

**Pull request merged**
