### PR TITLE
Make header responsive by adding hamburger button on smaller screens

### PR DESCRIPTION
**Pull request by grmbyrn**
### Description:
I have added a new SvelteKit component called `AnimatedHamburger`. This component provides a visually appealing animated hamburger menu that can be used for mobile navigation.

### Changes Made:

* Created a new Svelte component named `AnimatedHamburger.svelte`.
* Implemented the component in the `Header` component for mobile navigation.
* The menu icon has a responsive design.

### Usage:
To use the `AnimatedHamburger` component, include it in your Svelte files and pass the `isMenuOpen` and `toggleMenu` props as follows:

```
<AnimatedHamburger {isMenuOpen} {toggleMenu}>
  <!-- Your menu items go here -->
</AnimatedHamburger>
```

### Styles:
The styles include responsiveness, transitions, and theme-specific colors for a seamless integration with various themes.

### Accessibility:
* Utilised buttons for each list item in the mobile navigation menu for enhanced accessibility.
* Buttons provide better keyboard navigation and focus handling for users who rely on screen readers.

### CODE REVIEW

**Comment by cgbosse** [comment]
I just looked at it but there does not seem to show such a menu. @grmbyrn 

image

**Comment by grmbyrn** [comment]
Hi @cgbosse, as far as I know @josecelano has to review a change he suggested and which I implemented in [#115](https://github.com/torrust/torrust-website/pull/115). Then I can add this responsive header for review.

**Comment by josecelano** [comment]
> Hi @cgbosse, as far as I know @josecelano has to review a change he suggested and which I implemented in [#115](https://github.com/torrust/torrust-website/pull/115). Then I can add this responsive header for review.

Hi @grmbyrn, [done](https://github.com/torrust/torrust-website/pull/115).

**Comment by grmbyrn** [comment]
> Hi @grmbyrn, [done](https://github.com/torrust/torrust-website/pull/115).

Thanks @josecelano. I've made another pull request for the responsive header in [#122](https://github.com/torrust/torrust-website/pull/122) and will have another few pull requests to make if that one is okay.

**Pull request closed without merging**
