### PR TITLE
Add dependency to publish on GitHub pages

### PR DESCRIPTION
**Pull request by josecelano**
With this change you can deploy manually to GitHub Pages with the following:

```s
npm run build && npm run deploy
```

### CODE REVIEW

**Comment by josecelano** [comment]
Hey @matfantinel @da2ce7  It's published on https://torrust.github.io/torrust-website/. I will set up the [torrust.com](https://torrust.com) domain later. I have to ask @cgbosse to change the DNS.

**Comment by matfantinel** [comment]
This looks good! For the record the images on that link seem to be broken only because of the site being in a sub path. They should work once it's on torrust.com

**Review by matfantinel — APPROVED** [review]

**Comment by josecelano** [comment]
> This looks good! For the record, the images on that link seem to be broken only because of the site being in a sub path. They should work once it's on torrust.com

That could be because you have to change the base path in the configuration:

https://kit.svelte.dev/docs/adapter-static#github-pages

I did that, but I was getting a double subpath for other resources like this:

https://torrust.github.io/torrust-website/torrust-website

And the CSS was not loaded correctly. I thought it was not needed anymore. I will double-check it before merging this PR. It should work with both domains because it's a relative path.

**Comment by matfantinel** [comment]
@josecelano the CSS not loading is definitely weird, as it should be handled on build. As for the images, I think I'm using `images/image.jpg` everywhere in the website and I guess we could experiment with [paths](https://kit.svelte.dev/docs/configuration#paths) to see if that can be handled maybe in the <Image /> component itself

**Comment by josecelano** [comment]
> @josecelano the CSS not loading is definitely weird, as it should be handled on build. As for the images, I think I'm using `images/image.jpg` everywhere in the website and I guess we could experiment with [paths](https://kit.svelte.dev/docs/configuration#paths) to see if that can be handled maybe in the <Image /> component itself

Hi @matfantinel, I've tried to change the image paths to relative paths, but it does not work because the postbuild script changes them. There are a couple of places where the domain is hardcoded:

- https://github.com/torrust/torrust-website/blob/develop/package.json#L17
- https://github.com/torrust/torrust-website/blob/develop/src/lib/data/meta.ts#L5

We can keep it that way for now since we are not planning to reuse this site or use more than one domain. It should be fixed after setting up the domain, as you said.

But we could open a new issue to use an env var instead of hardcoding the domain as suggested by [svelte-kit documentation](https://kit.svelte.dev/docs/adapter-static#github-pages). That way you could specify the domain when you build the page:

```
BASE_PATH="/torrust-website" npm run build
```

In fact, in the documentation, the env var is only for the "base path" (subfolder, not including the domain). Maybe we can have a different one for the domain. But as I said, we can open an issue just for the record and set up the DNS for the torrust.com domain.

**Comment by matfantinel** [comment]
That's a great idea! I haven't seen/thought that about using the env variable. This would be a great thing to have upstream in the template too

**Pull request merged**
